application: listgames
version: 1
api_version: 1
runtime: python

handlers:
- url: /newgame
  script: viewcontroller.newgame
- url: /.+
  script: viewcontroller.game
- url: /
  script: viewcontroller.main
